//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuctionSystem.UsingBlockChain.StringResource {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AuctionSystem.UsingBlockChain.StringResource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Address과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AddressSearch과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AddressSearch {
            get {
                return ResourceManager.GetString("AddressSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Admin과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Amethyst과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Amethyst {
            get {
                return ResourceManager.GetString("Amethyst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Appraisal과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Appraisal {
            get {
                return ResourceManager.GetString("Appraisal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aquamarine과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Aquamarine {
            get {
                return ResourceManager.GetString("Aquamarine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AuctionSystem과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AuctionSystem {
            get {
                return ResourceManager.GetString("AuctionSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Before과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Before {
            get {
                return ResourceManager.GetString("Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bid과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Bid {
            get {
                return ResourceManager.GetString("Bid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BidCount과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BidCount {
            get {
                return ResourceManager.GetString("BidCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BidDetail과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BidDetail {
            get {
                return ResourceManager.GetString("BidDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BidPrice과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BidPrice {
            get {
                return ResourceManager.GetString("BidPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BidStatus과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BidStatus {
            get {
                return ResourceManager.GetString("BidStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BidTime과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BidTime {
            get {
                return ResourceManager.GetString("BidTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ⓒCopyright MegaAuction Inc. All right reserved.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create Auction과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CreateAuction {
            get {
                return ResourceManager.GetString("CreateAuction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CurrentPrice과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CurrentPrice {
            get {
                return ResourceManager.GetString("CurrentPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DeadlineTime과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DeadlineTime {
            get {
                return ResourceManager.GetString("DeadlineTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delivery과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Delivery {
            get {
                return ResourceManager.GetString("Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DelUser과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DelUser {
            get {
                return ResourceManager.GetString("DelUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deposit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Deposit {
            get {
                return ResourceManager.GetString("Deposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DepositDay과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DepositDay {
            get {
                return ResourceManager.GetString("DepositDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Desc과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Desc {
            get {
                return ResourceManager.GetString("Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dia과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Dia {
            get {
                return ResourceManager.GetString("Dia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Done과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Emerald과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Emerald {
            get {
                return ResourceManager.GetString("Emerald", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EndTime과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EndToCurrentDay과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EndToCurrentDay {
            get {
                return ResourceManager.GetString("EndToCurrentDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Etc과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Etc {
            get {
                return ResourceManager.GetString("Etc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Filter과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GoodsCurrentPrice (ETH)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GoodsCurrentPrice {
            get {
                return ResourceManager.GetString("GoodsCurrentPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GoodsName과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GoodsName {
            get {
                return ResourceManager.GetString("GoodsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GoodsState과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GoodsState {
            get {
                return ResourceManager.GetString("GoodsState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GoodsType과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GoodsType {
            get {
                return ResourceManager.GetString("GoodsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   High과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Id과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ing과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Ing {
            get {
                return ResourceManager.GetString("Ing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   InputMessage과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InputMessage {
            get {
                return ResourceManager.GetString("InputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   isAppraisal과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string isAppraisal {
            get {
                return ResourceManager.GetString("isAppraisal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   isntAppraisal과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string isntAppraisal {
            get {
                return ResourceManager.GetString("isntAppraisal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JewelryTypeOrder과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string JewelryTypeOrder {
            get {
                return ResourceManager.GetString("JewelryTypeOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Join과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Join {
            get {
                return ResourceManager.GetString("Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LastDay과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LastDay {
            get {
                return ResourceManager.GetString("LastDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LastDayOrder과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LastDayOrder {
            get {
                return ResourceManager.GetString("LastDayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Logout과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Low과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LowPriceOrder과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LowPriceOrder {
            get {
                return ResourceManager.GetString("LowPriceOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MaxPrice과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MaxPrice {
            get {
                return ResourceManager.GetString("MaxPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Middle과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Middle {
            get {
                return ResourceManager.GetString("Middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modify과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mypage과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Mypage {
            get {
                return ResourceManager.GetString("Mypage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Normal과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NormalUser과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NormalUser {
            get {
                return ResourceManager.GetString("NormalUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Opal과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Opal {
            get {
                return ResourceManager.GetString("Opal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Price과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pwd과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Pwd {
            get {
                return ResourceManager.GetString("Pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rare과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Rare {
            get {
                return ResourceManager.GetString("Rare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RareOrder과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RareOrder {
            get {
                return ResourceManager.GetString("RareOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ruby과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Ruby {
            get {
                return ResourceManager.GetString("Ruby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sapphire과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Sapphire {
            get {
                return ResourceManager.GetString("Sapphire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Separator {
            get {
                return ResourceManager.GetString("Separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StartDay과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StartDay {
            get {
                return ResourceManager.GetString("StartDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StartPrice과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StartPrice {
            get {
                return ResourceManager.GetString("StartPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Submit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tanzanite과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Tanzanite {
            get {
                return ResourceManager.GetString("Tanzanite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Trading과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Trading {
            get {
                return ResourceManager.GetString("Trading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TradingBefore과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TradingBefore {
            get {
                return ResourceManager.GetString("TradingBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TradingDone과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TradingDone {
            get {
                return ResourceManager.GetString("TradingDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UserLevel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UserLevel {
            get {
                return ResourceManager.GetString("UserLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VIP과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string VIP {
            get {
                return ResourceManager.GetString("VIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WelcomeMessage과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WelcomeUser과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WelcomeUser {
            get {
                return ResourceManager.GetString("WelcomeUser", resourceCulture);
            }
        }
    }
}
